gitea:
  admin:
    username: admin
    password: admin1234
    email: admin@ai-company.local

  config:
    server:
      DOMAIN: gitea.local
      ROOT_URL: http://gitea.local
    webhook:
      ALLOWED_HOST_LIST: "*"
    actions:
      ENABLED: true

service:
  http:
    type: NodePort
    nodePort: 30080

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

postgresql-ha:
  enabled: false

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        password: gitea
        database: gitea
        username: gitea
