loki:
  enabled: true
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  auth_enabled: false

singleBinary:
  replicas: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 250m

promtail:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m

grafana:
  enabled: false

test:
  enabled: false
